"""
Excel Exporter Module
Exports scanned system information to Excel format.
"""
import re
from datetime import datetime

# Import openpyxl components - will be available if the package is installed
try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
    from openpyxl.utils import get_column_letter
    from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False
    # Fallback regex for illegal XML characters (control characters not allowed in XML)
    ILLEGAL_CHARACTERS_RE = re.compile(r'[\x00-\x08\x0B\x0C\x0E-\x1F]')


class ExcelExporter:
    """Exporter for system information to Excel format."""
    
    # Note message for cells with removed illegal characters
    ILLEGAL_CHARS_NOTE = "Illegal characters removed"
    
    def __init__(self):
        self.workbook = None
    
    def _sanitize_value(self, value):
        """
        Sanitize a value by removing illegal XML characters.
        
        Args:
            value: The value to sanitize
            
        Returns:
            Tuple of (sanitized_value, had_illegal_chars)
        """
        if value is None:
            return ('', False)
        
        str_value = str(value)
        
        # Check if there are any illegal characters
        if ILLEGAL_CHARACTERS_RE.search(str_value):
            # Remove illegal characters
            sanitized = ILLEGAL_CHARACTERS_RE.sub('', str_value)
            return (sanitized, True)
        
        return (str_value, False)
    
    def export(self, cpe_data, output_file='system_scan_report.xlsx'):
        """
        Export CPE data to an Excel file.
        
        Args:
            cpe_data: List of CPE formatted dictionaries
            output_file: Output file path
        
        Returns:
            Path to the created Excel file
        """
        if not OPENPYXL_AVAILABLE:
            raise ImportError("openpyxl is required for Excel export. Install it with: pip install openpyxl")
        
        # Create workbook
        self.workbook = Workbook()
        ws = self.workbook.active
        ws.title = "System Scan Report"
        
        # Define styles
        header_font = Font(bold=True, color="FFFFFF", size=12)
        header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        
        cell_alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
        
        thin_border = Border(
            left=Side(style='thin'),
            right=Side(style='thin'),
            top=Side(style='thin'),
            bottom=Side(style='thin')
        )
        
        # Define headers (added Notes column for illegal character handling)
        headers = ['Type', 'Name', 'Vendor', 'Product', 'Version', 'CPE', 'Notes']
        
        # Write headers
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=header)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment
            cell.border = thin_border
        
        # Write data
        for row, item in enumerate(cpe_data, 2):
            row_had_illegal_chars = False
            
            # Sanitize and write each field
            fields = ['type', 'name', 'vendor', 'product', 'version', 'cpe']
            for col, field in enumerate(fields, 1):
                value, had_illegal = self._sanitize_value(item.get(field, ''))
                if had_illegal:
                    row_had_illegal_chars = True
                ws.cell(row=row, column=col, value=value).border = thin_border
            
            # Add note if illegal characters were removed
            note = self.ILLEGAL_CHARS_NOTE if row_had_illegal_chars else ""
            ws.cell(row=row, column=7, value=note).border = thin_border
            
            for col in range(1, 8):
                ws.cell(row=row, column=col).alignment = cell_alignment
        
        # Adjust column widths
        column_widths = {
            1: 25,   # Type
            2: 40,   # Name
            3: 20,   # Vendor
            4: 40,   # Product
            5: 30,   # Version
            6: 80,   # CPE
            7: 25,   # Notes
        }
        
        for col, width in column_widths.items():
            ws.column_dimensions[get_column_letter(col)].width = width
        
        # Add metadata sheet
        meta_ws = self.workbook.create_sheet(title="Scan Info")
        meta_ws['A1'] = "Scan Date:"
        meta_ws['B1'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        meta_ws['A2'] = "Total Items:"
        meta_ws['B2'] = len(cpe_data)
        meta_ws['A3'] = "Report Generated By:"
        meta_ws['B3'] = "System Scanner"
        
        # Style metadata sheet
        for row in range(1, 4):
            meta_ws.cell(row=row, column=1).font = Font(bold=True)
        
        meta_ws.column_dimensions['A'].width = 20
        meta_ws.column_dimensions['B'].width = 30
        
        # Add summary sheet
        summary_ws = self.workbook.create_sheet(title="Summary")
        
        # Count by type
        type_counts = {}
        for item in cpe_data:
            item_type = item.get('type', 'Unknown')
            # Simplify type names
            if 'Operating System' in item_type:
                category = 'Operating System'
            elif 'Hardware' in item_type:
                category = 'Hardware'
            elif 'Software' in item_type:
                category = 'Software'
            else:
                category = 'Other'
            
            type_counts[category] = type_counts.get(category, 0) + 1
        
        # Write summary headers
        summary_ws['A1'] = "Category"
        summary_ws['B1'] = "Count"
        summary_ws['A1'].font = header_font
        summary_ws['A1'].fill = header_fill
        summary_ws['B1'].font = header_font
        summary_ws['B1'].fill = header_fill
        
        # Write summary data
        for row, (category, count) in enumerate(sorted(type_counts.items()), 2):
            summary_ws.cell(row=row, column=1, value=category)
            summary_ws.cell(row=row, column=2, value=count)
        
        summary_ws.column_dimensions['A'].width = 20
        summary_ws.column_dimensions['B'].width = 15
        
        # Save workbook
        self.workbook.save(output_file)
        
        return output_file
    
    def export_detailed(self, os_info, hardware_info, software_list, cpe_data, 
                        output_file='detailed_system_report.xlsx'):
        """
        Export detailed system information to an Excel file with multiple sheets.
        
        Args:
            os_info: Dictionary containing OS information
            hardware_info: Dictionary containing hardware information
            software_list: List of software dictionaries
            cpe_data: List of CPE formatted dictionaries
            output_file: Output file path
        
        Returns:
            Path to the created Excel file
        """
        if not OPENPYXL_AVAILABLE:
            raise ImportError("openpyxl is required for Excel export. Install it with: pip install openpyxl")
        
        self.workbook = Workbook()
        
        # Define styles
        header_font = Font(bold=True, color="FFFFFF", size=11)
        header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        
        # === CPE Report Sheet ===
        ws_cpe = self.workbook.active
        ws_cpe.title = "CPE Report"
        self._write_cpe_sheet(ws_cpe, cpe_data, header_font, header_fill)
        
        # === OS Information Sheet ===
        ws_os = self.workbook.create_sheet(title="OS Information")
        self._write_os_sheet(ws_os, os_info, header_font, header_fill)
        
        # === Hardware Information Sheet ===
        ws_hw = self.workbook.create_sheet(title="Hardware Info")
        self._write_hardware_sheet(ws_hw, hardware_info, header_font, header_fill)
        
        # === Software List Sheet ===
        ws_sw = self.workbook.create_sheet(title="Software List")
        self._write_software_sheet(ws_sw, software_list, header_font, header_fill)
        
        # === Summary Sheet ===
        ws_summary = self.workbook.create_sheet(title="Summary")
        self._write_summary_sheet(ws_summary, os_info, hardware_info, software_list, cpe_data, header_font, header_fill)
        
        # Save workbook
        self.workbook.save(output_file)
        
        return output_file
    
    def _write_cpe_sheet(self, ws, cpe_data, header_font, header_fill):
        """Write CPE data to worksheet."""
        headers = ['Type', 'Name', 'Vendor', 'Product', 'Version', 'CPE', 'Notes']
        
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=header)
            cell.font = header_font
            cell.fill = header_fill
        
        for row, item in enumerate(cpe_data, 2):
            row_had_illegal_chars = False
            
            # Sanitize and write each field
            fields = ['type', 'name', 'vendor', 'product', 'version', 'cpe']
            for col, field in enumerate(fields, 1):
                value, had_illegal = self._sanitize_value(item.get(field, ''))
                if had_illegal:
                    row_had_illegal_chars = True
                ws.cell(row=row, column=col, value=value)
            
            # Add note if illegal characters were removed
            note = self.ILLEGAL_CHARS_NOTE if row_had_illegal_chars else ""
            ws.cell(row=row, column=7, value=note)
        
        # Adjust widths
        widths = [25, 40, 20, 40, 30, 80, 25]
        for i, width in enumerate(widths, 1):
            ws.column_dimensions[get_column_letter(i)].width = width
    
    def _write_os_sheet(self, ws, os_info, header_font, header_fill):
        """Write OS information to worksheet."""
        ws.cell(row=1, column=1, value="Property").font = header_font
        ws.cell(row=1, column=1).fill = header_fill
        ws.cell(row=1, column=2, value="Value").font = header_font
        ws.cell(row=1, column=2).fill = header_fill
        ws.cell(row=1, column=3, value="Notes").font = header_font
        ws.cell(row=1, column=3).fill = header_fill
        
        row = 2
        for key, value in os_info.items():
            key_sanitized, key_had_illegal = self._sanitize_value(key)
            value_sanitized, value_had_illegal = self._sanitize_value(value)
            
            ws.cell(row=row, column=1, value=key_sanitized)
            ws.cell(row=row, column=2, value=value_sanitized)
            
            note = self.ILLEGAL_CHARS_NOTE if (key_had_illegal or value_had_illegal) else ""
            ws.cell(row=row, column=3, value=note)
            row += 1
        
        ws.column_dimensions['A'].width = 20
        ws.column_dimensions['B'].width = 50
        ws.column_dimensions['C'].width = 25
    
    def _write_hardware_sheet(self, ws, hardware_info, header_font, header_fill):
        """Write hardware information to worksheet."""
        ws.cell(row=1, column=1, value="Component").font = header_font
        ws.cell(row=1, column=1).fill = header_fill
        ws.cell(row=1, column=2, value="Property").font = header_font
        ws.cell(row=1, column=2).fill = header_fill
        ws.cell(row=1, column=3, value="Value").font = header_font
        ws.cell(row=1, column=3).fill = header_fill
        ws.cell(row=1, column=4, value="Notes").font = header_font
        ws.cell(row=1, column=4).fill = header_fill
        
        row = 2
        for component, data in hardware_info.items():
            if isinstance(data, dict):
                for key, value in data.items():
                    comp_sanitized, comp_had_illegal = self._sanitize_value(component.upper())
                    key_sanitized, key_had_illegal = self._sanitize_value(key)
                    value_sanitized, value_had_illegal = self._sanitize_value(value)
                    
                    ws.cell(row=row, column=1, value=comp_sanitized)
                    ws.cell(row=row, column=2, value=key_sanitized)
                    ws.cell(row=row, column=3, value=value_sanitized)
                    
                    note = self.ILLEGAL_CHARS_NOTE if (comp_had_illegal or key_had_illegal or value_had_illegal) else ""
                    ws.cell(row=row, column=4, value=note)
                    row += 1
            elif isinstance(data, list):
                for i, item in enumerate(data):
                    if isinstance(item, dict):
                        for key, value in item.items():
                            comp_name = f"{component.upper()} #{i+1}"
                            comp_sanitized, comp_had_illegal = self._sanitize_value(comp_name)
                            key_sanitized, key_had_illegal = self._sanitize_value(key)
                            value_sanitized, value_had_illegal = self._sanitize_value(value)
                            
                            ws.cell(row=row, column=1, value=comp_sanitized)
                            ws.cell(row=row, column=2, value=key_sanitized)
                            ws.cell(row=row, column=3, value=value_sanitized)
                            
                            note = self.ILLEGAL_CHARS_NOTE if (comp_had_illegal or key_had_illegal or value_had_illegal) else ""
                            ws.cell(row=row, column=4, value=note)
                            row += 1
        
        ws.column_dimensions['A'].width = 20
        ws.column_dimensions['B'].width = 20
        ws.column_dimensions['C'].width = 50
        ws.column_dimensions['D'].width = 25
    
    def _write_software_sheet(self, ws, software_list, header_font, header_fill):
        """Write software list to worksheet."""
        headers = ['Name', 'Version', 'Vendor', 'Type', 'Notes']
        
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=header)
            cell.font = header_font
            cell.fill = header_fill
        
        for row, software in enumerate(software_list, 2):
            if 'error' not in software:
                row_had_illegal_chars = False
                
                fields = ['name', 'version', 'vendor', 'type']
                for col, field in enumerate(fields, 1):
                    value, had_illegal = self._sanitize_value(software.get(field, ''))
                    if had_illegal:
                        row_had_illegal_chars = True
                    ws.cell(row=row, column=col, value=value)
                
                note = self.ILLEGAL_CHARS_NOTE if row_had_illegal_chars else ""
                ws.cell(row=row, column=5, value=note)
        
        ws.column_dimensions['A'].width = 50
        ws.column_dimensions['B'].width = 30
        ws.column_dimensions['C'].width = 30
        ws.column_dimensions['D'].width = 15
        ws.column_dimensions['E'].width = 25
    
    def _write_summary_sheet(self, ws, os_info, hardware_info, software_list, cpe_data, header_font, header_fill):
        """Write summary to worksheet."""
        ws.cell(row=1, column=1, value="System Scan Summary").font = Font(bold=True, size=14)
        ws.merge_cells('A1:B1')
        
        ws.cell(row=3, column=1, value="Scan Date:").font = Font(bold=True)
        ws.cell(row=3, column=2, value=datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        
        ws.cell(row=5, column=1, value="Operating System:").font = Font(bold=True)
        platform_value, _ = self._sanitize_value(os_info.get('platform', 'Unknown'))
        ws.cell(row=5, column=2, value=platform_value)
        
        ws.cell(row=7, column=1, value="Statistics:").font = Font(bold=True, size=12)
        ws.cell(row=8, column=1, value="Total CPE Entries:")
        ws.cell(row=8, column=2, value=len(cpe_data))
        ws.cell(row=9, column=1, value="Software Packages:")
        ws.cell(row=9, column=2, value=len([s for s in software_list if 'error' not in s]))
        ws.cell(row=10, column=1, value="Hardware Components:")
        hw_count = sum(1 for v in hardware_info.values() if isinstance(v, dict))
        hw_count += sum(len(v) for v in hardware_info.values() if isinstance(v, list))
        ws.cell(row=10, column=2, value=hw_count)
        
        ws.column_dimensions['A'].width = 25
        ws.column_dimensions['B'].width = 40
